# Provider Toggle (Choice: twilio OR msg91)
# Use the Environment Variable OTP_SERVICE_PROVIDER to switch in the cloud
otp.service.provider=${OTP_SERVICE_PROVIDER:msg91}

# Twilio Configuration
twilio.account-sid=${TWILIO_ACCOUNT_SID:YOUR_SID_HERE}
twilio.auth-token=${TWILIO_AUTH_TOKEN:YOUR_TOKEN_HERE}
twilio.phone-number=${TWILIO_PHONE_NUMBER:YOUR_NUMBER_HERE}

# MSG91 Configuration
msg91.auth-key=${MSG91_AUTH_KEY:508524ARKre45QaR69dde447P1}
msg91.template-id=${MSG91_TEMPLATE_ID:69dde52893f9ced38f0ff652}
msg91.sender-id=${MSG91_SENDER_ID:www}
